In [2]:
import numpy as np
import time
import sys
import matplotlib.pyplot as plt

s= range(1000)

In [3]:
a = np.array([[1,2,3],[6,7,8]])
#gives dimesnion
a.shape
#give total no of elements
a.size
#gives transpose
t = np.transpose(a)
print(t)
i = np.invert(a)
print(i)
ab=np.abs(a)
print (ab)

[[1 6]
 [2 7]
 [3 8]]
[[-2 -3 -4]
 [-7 -8 -9]]
[[1 2 3]
 [6 7 8]]


In [94]:
#differnt matrix types
z = np.zeros((3,8)).astype(int)
#ones matrix
o = np.ones((2,5))
t =np.transpose(o)
ot=0*t
r = np.random.random((2,5))
ro=r*o
print(ro)
print(r)

[[0.68527433 0.70416168 0.18784025 0.67040872 0.49128316]
 [0.61575637 0.87106401 0.08465447 0.8653582  0.59269246]]
[[0.68527433 0.70416168 0.18784025 0.67040872 0.49128316]
 [0.61575637 0.87106401 0.08465447 0.8653582  0.59269246]]


In [9]:
a= np.array([(1,2,3),(6,7,8)])
print(a)

[[1 2 3]
 [6 7 8]]


(2, 3)

In [10]:
a.dtype

dtype('int64')

In [11]:
a.ndim

2

In [12]:
a.itemsize

8

In [13]:
a.size

6

In [14]:
a.shape

(2, 3)

In [15]:
#reshap and scalling
a.reshape(3,2)

array([[1, 2],
       [3, 6],
       [7, 8]])

In [18]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [6],
       [7],
       [8]])

In [25]:
#slicing
a[0:,2]

array([3, 8])

In [33]:
#linspace between two values 
a= np.linspace(1,1000,8).astype(int)
print (a)

[   1  143  286  429  571  714  857 1000]


In [35]:
#minium max
a.max()

1000

In [36]:
a.min()

1

In [37]:
a.mean()

500.125

In [38]:
a.sum()

4001

In [72]:
#sum of row and columns
a=np.array([(1,5,8),(6,10,15)])
print (a)
print(a.sum(axis=1))

print(a.sum(axis=0))

[[ 1  5  8]
 [ 6 10 15]]
[14 31]
[ 7 15 23]


In [51]:
#standard dev and 

print (np.std(a))

4.349329450233296


In [73]:
#stacking vertically
b= np.ones((2,3))
np.vstack((b,a))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  5.,  8.],
       [ 6., 10., 15.]])

In [62]:
np.hstack((b,a))

array([[ 1.,  1.,  1.,  1.,  5.,  8.],
       [ 1.,  1.,  1.,  6., 10., 15.]])

In [67]:
#change into 1-d array.
print(np.ravel(a)+np.ravel(b))

[ 2.  6.  9.  7. 11. 16.]


In [81]:
#cosine and sine function
a= np.array(([1,2,3]))
b= np.array(([6,2.5,8]))


# plt.plot(x,y)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [76]:
plt.show()

In [84]:
#exponential
print(np.exp(a))
#logerithm
print(np.log(b))
#natural log
print(np.log10(b))

[ 2.71828183  7.3890561  20.08553692]
[1.79175947 0.91629073 2.07944154]
[0.77815125 0.39794001 0.90308999]
